version: '{build}'

environment:
  packageVersion: 0.0.1

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - develop
  - release

configuration: Release

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true

build:
  publish_nuget: true

build_script:
- ps: .\Build.ps1

artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  name: production
  api_key:
    secure: '2K5EQwNNYpt5GMRVKxHTihZO2MZCUSbsngmYo63XPO73UoX0n7INS/4OGIrZ3mMe'
  on:
    branch: master
    appveyor_repo_tag: true
